apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- HyperConverged.yaml
- StorageProfile/
# Disabled, installed by hand
#- Namespace.yaml
#- OperatorGroup.yaml
#- Subscription.yaml
