apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  customization:
    customLogoFile:
      key: console-custom-logo.png
      name: console-custom-logo
    customProductName: "üå™Ô∏è OCP1 - StormShift"