apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- coe-bridge-via-eno2.yaml
- coe-bridge-via-enp4s0f1.yaml
- coe-bridge-via-enp80s0f1.yaml
- coe-bridge-via-enp9s0.yaml
- coe-bridge-via-enp135s0.yaml
