apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Proxy/cluster.yaml
  - Console/cluster.yaml
  - ConsoleNotification/
  - OAuth/cluster.yaml
  - MachineConfig/
  - StorageClass/
  - Config/
  - Group/
  - ClusterRoleBinding/
  - Scheduler/
  - Node/
  - Project/
