apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stormshift-kubevirt-redfish
  namespace: openshift-gitops
spec:
  project: default
  sources:
    - chart: kubevirt-redfish
      repoURL: https://v1k0d3n.github.io/charts
      targetRevision: 0.2.3
      helm:
        valueFiles:
          - $config-repo/isar-apps/kubevirt-redfish/values4helmchart.yaml

# Need this source for the values file:
    - repoURL: https://github.com/stormshift/clusters.git
      path: 'isar-apps/kubevirt-redfish'
      targetRevision: main
      ref: config-repo

  destination:
    server: https://kubernetes.default.svc
